#!/bin/bash
# requres jq, az cli
# must already be logged into az cli
SUBSCRIPTION_ID="$(az account show --query id --output tsv)"
ACI_NAME=dagster-daemon
ACI_IMAGE=cfaprdbatchcr.azurecr.io/cfa-dagster-infra:latest
RESOURCE_GROUP=ext-edav-cfa-prd
LA_RESOURCE_GROUP=DefaultResourceGroup-EUS
ACI_ACR_IDENTITY="/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dagster-daemon-mi"
ACI_SUBNET_ID="/subscriptions/$SUBSCRIPTION_ID/resourceGroups/EXT-EDAV-CFA-Network-PRD/providers/Microsoft.Network/virtualNetworks/EXT_EDAV_CFA_VNET_PRD/subnets/EXT_EDAV_CFA_CONTAINER_INSTANCE_PRD"
# this is the account name and the file share name
AZURE_FILE_SHARE=cfadagster
AZURE_FILE_VOLUME_ACCOUNT_KEY=$(az storage account keys list --resource-group "$RESOURCE_GROUP" --account-name "$AZURE_FILE_SHARE" | jq -r '.[0].value')
LOG_ANALYTICS_WORKSPACE_ID=$(az monitor log-analytics workspace show --resource-group $LA_RESOURCE_GROUP --workspace-name "DefaultWorkspace-$SUBSCRIPTION_ID-EUS" --query customerId --output tsv)
LOG_ANALYTICS_WORKSPACE_KEY=$(az monitor log-analytics workspace get-shared-keys --resource-group $LA_RESOURCE_GROUP --workspace-name "DefaultWorkspace-$SUBSCRIPTION_ID-EUS" --query primarySharedKey --output tsv)
cat > /tmp/aci-daemon.yaml << EOF
# This file is generated by infra/deploy-dagster-daemon-aci.sh
# Do not edit this file directly.
location: eastus
identity:
  type: UserAssigned
  userAssignedIdentities:
    "$ACI_ACR_IDENTITY": {}
properties:
  containers:
    - name: "$ACI_NAME"
      properties:
        image: "$ACI_IMAGE"
        command:
          - "dagster-daemon"
          - "run"
        environmentVariables:
          - name: DAGSTER_HOME
            value: /opt/dagster/dagster_home
          - name: DAGSTER_USER
            value: prod
        ports:
          - port: 80
            protocol: TCP
        resources:
          requests:
            cpu: 2
            memoryInGB: 4
        volumeMounts:
          - name: dagster-volume
            mountPath: /opt/dagster
  osType: Linux
  restartPolicy: Always
  subnetIds:
    - id: "$ACI_SUBNET_ID"
  dnsConfig:
    nameServers:
      - "172.45.0.36"
      - "172.45.0.37"
  diagnostics:
    logAnalytics:
      workspaceId: "$LOG_ANALYTICS_WORKSPACE_ID"
      workspaceKey: "$LOG_ANALYTICS_WORKSPACE_KEY"
  volumes:
    - name: dagster-volume
      azureFile:
        shareName: "$AZURE_FILE_SHARE"
        storageAccountName: "$AZURE_FILE_SHARE"
        storageAccountKey: "$AZURE_FILE_VOLUME_ACCOUNT_KEY"
  imageRegistryCredentials:
    - server: "cfaprdbatchcr.azurecr.io"
      identity: "$ACI_ACR_IDENTITY"
EOF

az container create \
  --resource-group "$RESOURCE_GROUP" \
  --name "$ACI_NAME" \
  --file /tmp/aci-daemon.yaml
