name: Build cfa-dagster

on:
  pull_request:
    branches: [main]
    paths:
      - pyproject.toml
      - uv.lock
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build
